<?php
require_once($_SERVER['DOCUMENT_ROOT'].'/config.php');
require_once('Func.php');
require_once(SYSTEM.'General/General.php');
$db=new General();
$GoogleAds=new GoogleAds();
date_default_timezone_set('Europe/London');
$Tarih1 = date('Y-m-d'); // Geçerli tarih

// Bir yıl geriye almak için strtotime ve date kullanın
$Tarih1BirYilOncesi = date('Y-m-d', strtotime($Tarih1 . ' -1 year'));

$Tarih=date('Y-m-d');


function turkceToIngilizce($metin) {
    $harfDizisi = array(
        'ç' => 'c', 'Ç' => 'C',
        'ğ' => 'g', 'Ğ' => 'G',
        'ı' => 'i', 'İ' => 'I',
        'ş' => 's', 'Ş' => 'S',
        'ö' => 'o', 'Ö' => 'O',
        'ü' => 'u', 'Ü' => 'U'
    );

    // Türkçe karakterleri İngilizce karakterlere dönüştür
    $metin = strtr($metin, $harfDizisi);

    return $metin;
}

$sorgu = '{
  "pageSize": 10000,
  "query": "
  SELECT


search_term_view.resource_name,

search_term_view.search_term,

search_term_view.status



FROM search_term_view
WHERE segments.date BETWEEN \''.$Tarih1BirYilOncesi.'\' AND \''.$Tarih.'\'

  "
}';



$sorguanahtarkelime = '{
  "pageSize": 1000,
  "query": "
    SELECT
           ad_group_criterion.keyword.text
    FROM keyword_view
    WHERE segments.date BETWEEN \''.$Tarih1BirYilOncesi.'\' AND \''.$Tarih.'\'

  "
}';



$GoogleSystem = $db->Query('Settings',['AccessToken' => ['$ne' => null]], [], 'TEK');
$GoogleId=$_GET["GoogleId"];
$AccountValue = $db->Query('Companies',['GoogleId' => (int)$GoogleId], [], 'TEK');

  $AccountId=$AccountValue["GoogleId"];
  $CompaniesCode=$AccountValue["CompanyCode"];
  $Commission=$AccountValue["Commission"];
  $SuankiButce=$AccountValue["google_ads_butce"];



  $GoogelSonuclarAnahtarkelime=$GoogleAds->googleistek(Google_DEVELOPER_TOKEN,Google_ID,$GoogleSystem['AccessToken'],$AccountId,$sorguanahtarkelime);





$parcalabir = array();

foreach ($GoogelSonuclarAnahtarkelime["results"] as $key => $valuex) {
    $parcalabir[]= explode(" ",strtolower(turkceToIngilizce($valuex["adGroupCriterion"]["keyword"]["text"])));
}
//$GoogleHesaplari=$db->cek("adminuser","where google_ads_id IS NOT NULL","COK");
$GoogelSonuclar=$GoogleAds->googleistek(Google_DEVELOPER_TOKEN,Google_ID,$GoogleSystem['AccessToken'],$AccountId,$sorgu);

$parcala = array();
foreach ($GoogelSonuclar["results"] as $key => $value) {
    $parcala[]= explode(" ",strtolower(turkceToIngilizce($value["searchTermView"]["searchTerm"])));
}

$iller = array(
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce",

);

$ilceler = array("Seyhan",
  "Ceyhan",
  "Feke",
  "Karaisalı",
  "Karataş",
  "Kozan",
  "Pozantı",
  "Saimbeyli",
  "Tufanbeyli",
  "Yumurtalık",
  "Yüreğir",
  "Aladağ",
  "İmamoğlu",
  "Sarıçam",
  "Çukurova",
  "Adıyaman",
  "Besni",
  "Çelikhan",
  "Gerger",
  "Gölbaşı",
  "Kahta",
  "Samsat",
  "Sincik",
  "Tut",
  "Afyonkarahisar",
  "Bolvadin",
  "Çay",
  "Dazkırı",
  "Dinar",
  "Emirdağ",
  "İhsaniye",
  "Sandıklı",
  "Sinanpaşa",
  "Sultandağı",
  "Şuhut",
  "Başmakçı",
  "Bayat",
  "İscehisar",
  "Çobanlar",
  "Evciler",
  "Hocalar",
  "Kızılören",
  "Ağrı",
  "Diyadin",
  "Doğubayazıt",
  "Eleşkirt",
  "Hamur",
  "Patnos",
  "Taşlıçay",
  "Tutak",
  "Amasya",
  "Göynücek",
  "Gümüşhacıköy",
  "Merzifon",
  "Suluova",
  "Taşova",
  "Hamamözü",
  "Altındağ",
  "Ayaş",
  "Bala",
  "Beypazarı",
  "Çamlıdere",
  "Çankaya",
  "Çubuk",
  "Elmadağ",
  "Güdül",
  "Haymana",
  "Kalecik",
  "Kızılcahamam",
  "Nallıhan",
  "Polatlı",
  "Şereflikoçhisar",
  "Yenimahalle",
  "Gölbaşı",
  "Keçiören",
  "Mamak",
  "Sincan",
  "Kazan",
  "Akyurt",
  "Etimesgut",
  "Evren",
  "Pursaklar",
  "Akseki",
  "Alanya",
  "Elmalı",
  "Finike",
  "Gazipaşa",
  "Gündoğmuş",
  "Kaş",
  "Korkuteli",
  "Kumluca",
  "Manavgat",
  "Serik",
  "Demre",
  "İbradı",
  "Kemer",
  "Aksu",
  "Döşemealtı",
  "Kepez",
  "Konyaaltı",
  "Muratpaşa",
  "Ardanuç",
  "Arhavi",
  "Artvin",
  "Borçka",
  "Hopa",
  "Şavşat",
  "Yusufeli",
  "Murgul",
  "Bozdoğan",
  "Çine",
  "Germencik",
  "Karacasu",
  "Koçarlı",
  "Kuşadası",
  "Kuyucak",
  "Nazilli",
  "Söke",
  "Sultanhisar",
  "Yenipazar",
  "Buharkent",
  "İncirliova",
  "Karpuzlu",
  "Köşk",
  "Didim",
  "Efeler",
  "Ayvalık",
  "Balya",
  "Bandırma",
  "Bigadiç",
  "Burhaniye",
  "Dursunbey",
  "Edremit",
  "Erdek",
  "Gönen",
  "Havran",
  "İvrindi",
  "Kepsut",
  "Manyas",
  "Savaştepe",
  "Sındırgı",
  "Susurluk",
  "Marmara",
  "Gömeç",
  "Altıeylül",
  "Karesi",
  "Bilecik",
  "Bozüyük",
  "Gölpazarı",
  "Osmaneli",
  "Pazaryeri",
  "Söğüt",
  "Yenipazar",
  "İnhisar",
  "Bingöl",
  "Genç",
  "Karlıova",
  "Kiğı",
  "Solhan",
  "Adaklı",
  "Yayladere",
  "Yedisu",
  "Adilcevaz",
  "Ahlat",
  "Bitlis",
  "Hizan",
  "Mutki",
  "Tatvan",
  "Güroymak",
  "Bolu",
  "Gerede",
  "Göynük",
  "Kıbrıscık",
  "Mengen",
  "Mudurnu",
  "Seben",
  "Dörtdivan",
  "Yeniçağa",
  "Ağlasun",
  "Bucak",
  "Burdur",
  "Gölhisar",
  "Tefenni",
  "Yeşilova",
  "Karamanlı",
  "Kemer",
  "Altınyayla",
  "Çavdır",
  "Çeltikçi",
  "Gemlik",
  "İnegöl",
  "İznik",
  "Karacabey",
  "Keles",
  "Mudanya",
  "Mustafakemalpaşa",
  "Orhaneli",
  "Orhangazi",
  "Yenişehir",
  "Büyükorhan",
  "Harmancık",
  "Nilüfer",
  "Osmangazi",
  "Yıldırım",
  "Gürsu",
  "Kestel",
  "Ayvacık",
  "Bayramiç",
  "Biga",
  "Bozcaada",
  "Çan",
  "Çanakkale",
  "Eceabat",
  "Ezine",
  "Gelibolu",
  "Gökçeada",
  "Lapseki",
  "Yenice",
  "Çankırı",
  "Çerkeş",
  "Eldivan",
  "Ilgaz",
  "Kurşunlu",
  "Orta",
  "Şabanözü",
  "Yapraklı",
  "Atkaracalar",
  "Kızılırmak",
  "Bayramören",
  "Korgun",
  "Alaca",
  "Bayat",
  "Çorum",
  "İskilip",
  "Kargı",
  "Mecitözü",
  "Ortaköy",
  "Osmancık",
  "Sungurlu",
  "Boğazkale",
  "Uğurludağ",
  "Dodurga",
  "Laçin",
  "Oğuzlar",
  "Acıpayam",
  "Buldan",
  "Çal",
  "Çameli",
  "Çardak",
  "Çivril",
  "Güney",
  "Kale",
  "Sarayköy",
  "Tavas",
  "Babadağ",
  "Bekilli",
  "Honaz",
  "Serinhisar",
  "Pamukkale",
  "Baklan",
  "Beyağaç",
  "Bozkurt",
  "efendi",
  "Bismil",
  "Çermik",
  "Çınar",
  "Çüngüş",
  "Dicle",
  "Ergani",
  "Hani",
  "Hazro",
  "Kulp",
  "Lice",
  "Silvan",
  "Eğil",
  "Kocaköy",
  "Bağlar",
  "Kayapınar",
  "Sur",
  "Yenişehir",
  "Edirne",
  "Enez",
  "Havsa",
  "İpsala",
  "Keşan",
  "Lalapaşa",
  "Meriç",
  "Uzunköprü",
  "Süloğlu",
  "Ağın",
  "Baskil",
  "Elazığ",
  "Karakoçan",
  "Keban",
  "Maden",
  "Palu",
  "Sivrice",
  "Arıcak",
  "Kovancılar",
  "Alacakaya",
  "Çayırlı",
  "Erzincan",
  "İliç",
  "Kemah",
  "Kemaliye",
  "Refahiye",
  "Tercan",
  "Üzümlü",
  "Otlukbeli",
  "Aşkale",
  "Çat",
  "Hınıs",
  "Horasan",
  "İspir",
  "Karayazı",
  "Narman",
  "Oltu",
  "Olur",
  "Pasinler",
  "Şenkaya",
  "Tekman",
  "Tortum",
  "Karaçoban",
  "Uzundere",
  "Pazaryolu",
  "Aziziye",
  "Köprüköy",
  "Palandöken",
  "Yakutiye",
  "Çifteler",
  "Mahmudiye",
  "Mihalıççık",
  "Sarıcakaya",
  "Seyitgazi",
  "Sivrihisar",
  "Alpu",
  "Beylikova",
  "İnönü",
  "Günyüzü",
  "Han",
  "Mihalgazi",
  "Odunpazarı",
  "Tepebaşı",
  "Araban",
  "İslahiye",
  "Nizip",
  "Oğuzeli",
  "Yavuzeli",
  "Şahinbey",
  "Şehitkamil",
  "Karkamış",
  "Nurdağı",
  "Alucra",
  "Bulancak",
  "Dereli",
  "Espiye",
  "Eynesil",
  "Giresun",
  "Görele",
  "Keşap",
  "Şebinkarahisar",
  "Tirebolu",
  "Piraziz",
  "Yağlıdere",
  "Çamoluk",
  "Çanakçı",
  "Doğankent",
  "Güce",
  "Gümüşhane",
  "Kelkit",
  "Şiran",
  "Torul",
  "Köse",
  "Kürtün",
  "Çukurca",
  "Hakkari",
  "Şemdinli",
  "Yüksekova",
  "Altınözü",
  "Dörtyol",
  "Hassa",
  "İskenderun",
  "Kırıkhan",
  "Reyhanlı",
  "Samandağ",
  "Yayladağı",
  "Erzin",
  "Belen",
  "Kumlu",
  "Antakya",
  "Arsuz",
  "Defne",
  "Payas",
  "Atabey",
  "Eğirdir",
  "Gelendost",
  "Isparta",
  "Keçiborlu",
  "Senirkent",
  "Sütçüler",
  "Şarkikaraağaç",
  "Uluborlu",
  "Yalvaç",
  "Aksu",
  "Gönen",
  "Yenişarbademli",
  "Anamur",
  "Erdemli",
  "Gülnar",
  "Mut",
  "Silifke",
  "Tarsus",
  "Aydıncık",
  "Bozyazı",
  "Çamlıyayla",
  "Akdeniz",
  "Mezitli",
  "Toroslar",
  "Yenişehir",
  "Adalar",
  "Bakırköy",
  "Beşiktaş",
  "Beykoz",
  "Beyoğlu",
  "Çatalca",
  "Eyüp",
  "Fatih",
  "Gaziosmanpaşa",
  "Kadıköy",
  "Kartal",
  "Sarıyer",
  "Silivri",
  "Şile",
  "Şişli",
  "Üsküdar",
  "Zeytinburnu",
  "Büyükçekmece",
  "Kağıthane",
  "Küçükçekmece",
  "Pendik",
  "Ümraniye",
  "Bayrampaşa",
  "Avcılar",
  "Bağcılar",
  "Bahçelievler",
  "Güngören",
  "Maltepe",
  "Sultanbeyli",
  "Tuzla",
  "Esenler",
  "Arnavutköy",
  "Ataşehir",
  "Başakşehir",
  "Beylikdüzü",
  "Çekmeköy",
  "Esenyurt",
  "Sancaktepe",
  "Sultangazi",
  "Aliağa",
  "Bayındır",
  "Bergama",
  "Bornova",
  "Çeşme",
  "Dikili",
  "Foça",
  "Karaburun",
  "Karşıyaka",
  "Kemalpaşa",
  "Kınık",
  "Kiraz",
  "Menemen",
  "Ödemiş",
  "Seferihisar",
  "Selçuk",
  "Tire",
  "Torbalı",
  "Urla",
  "Beydağ",
  "Buca",
  "Konak",
  "Menderes",
  "Balçova",
  "Çiğli",
  "Gaziemir",
  "Narlıdere",
  "Güzelbahçe",
  "Bayraklı",
  "Karabağlar",
  "Arpaçay",
  "Digor",
  "Kağızman",
  "Kars",
  "Sarıkamış",
  "Selim",
  "Susuz",
  "Akyaka",
  "Abana",
  "Araç",
  "Azdavay",
  "Bozkurt",
  "Cide",
  "Çatalzeytin",
  "Daday",
  "Devrekani",
  "İnebolu",
  "Kastamonu",
  "Küre",
  "Taşköprü",
  "Tosya",
  "İhsangazi",
  "Pınarbaşı",
  "Şenpazar",
  "Ağlı",
  "Doğanyurt",
  "Hanönü",
  "Seydiler",
  "Bünyan",
  "Develi",
  "Felahiye",
  "İncesu",
  "Pınarbaşı",
  "Sarıoğlan",
  "Sarız",
  "Tomarza",
  "Yahyalı",
  "Yeşilhisar",
  "Akkışla",
  "Talas",
  "Kocasinan",
  "Melikgazi",
  "Hacılar",
  "Özvatan",
  "Babaeski",
  "Demirköy",
  "Kırklareli",
  "Kofçaz",
  "Lüleburgaz",
  "Pehlivanköy",
  "Pınarhisar",
  "Vize",
  "Çiçekdağı",
  "Kaman",
  "Kırşehir",
  "Mucur",
  "Akpınar",
  "Akçakent",
  "Boztepe",
  "Gebze",
  "Gölcük",
  "Kandıra",
  "Karamürsel",
  "Körfez",
  "Derince",
  "Başiskele",
  "Çayırova",
  "Darıca",
  "Dilovası",
  "İzmit",
  "Kartepe",
  "Akşehir",
  "Beyşehir",
  "Bozkır",
  "Cihanbeyli",
  "Çumra",
  "Doğanhisar",
  "Ereğli",
  "Hadim",
  "Ilgın",
  "Kadınhanı",
  "Karapınar",
  "Kulu",
  "Sarayönü",
  "Seydişehir",
  "Yunak",
  "Akören",
  "Altınekin",
  "Derebucak",
  "Hüyük",
  "Karatay",
  "Meram",
  "Selçuklu",
  "Taşkent",
  "Ahırlı",
  "Çeltik",
  "Derbent",
  "Emirgazi",
  "Güneysınır",
  "Halkapınar",
  "Tuzlukçu",
  "Yalıhüyük",
  "Altıntaş",
  "Domaniç",
  "Emet",
  "Gediz",
  "Kütahya",
  "Simav",
  "Tavşanlı",
  "Aslanapa",
  "Dumlupınar",
  "Hisarcık",
  "Şaphane",
  "Çavdarhisar",
  "Pazarlar",
  "Akçadağ",
  "Arapgir",
  "Arguvan",
  "Darende",
  "Doğanşehir",
  "Hekimhan",
  "Pütürge",
  "Yeşilyurt",
  "Battalgazi",
  "Doğanyol",
  "Kale",
  "Kuluncak",
  "Yazıhan",
  "Akhisar",
  "Alaşehir",
  "Demirci",
  "Gördes",
  "Kırkağaç",
  "Kula",
  "Salihli",
  "Sarıgöl",
  "Saruhanlı",
  "Selendi",
  "Soma",
  "Turgutlu",
  "Ahmetli",
  "Gölmarmara",
  "Köprübaşı",
  "Şehzadeler",
  "Yunusemre",
  "Afşin",
  "Andırın",
  "Elbistan",
  "Göksun",
  "Pazarcık",
  "Türkoğlu",
  "Çağlayancerit",
  "Ekinözü",
  "Nurhak",
  "Dulkadiroğlu",
  "Onikişubat",
  "Derik",
  "Kızıltepe",
  "Mazıdağı",
  "Midyat",
  "Nusaybin",
  "Ömerli",
  "Savur",
  "Dargeçit",
  "Yeşilli",
  "Artuklu",
  "Bodrum",
  "Datça",
  "Fethiye",
  "Köyceğiz",
  "Marmaris",
  "Milas",
  "Ula",
  "Yatağan",
  "Dalaman",
  "Ortaca",
  "Kavaklıdere",
  "Menteşe",
  "Seydikemer",
  "Bulanık",
  "Malazgirt",
  "Muş",
  "Varto",
  "Hasköy",
  "Korkut",
  "Avanos",
  "Derinkuyu",
  "Gülşehir",
  "Hacıbektaş",
  "Kozaklı",
  "Nevşehir",
  "Ürgüp",
  "Acıgöl",
  "Bor",
  "Çamardı",
  "Niğde",
  "Ulukışla",
  "Altunhisar",
  "Çiftlik",
  "Akkuş",
  "Aybastı",
  "Fatsa",
  "Gölköy",
  "Korgan",
  "Kumru",
  "Mesudiye",
  "Perşembe",
  "Ulubey",
  "Ünye",
  "Gülyalı",
  "Gürgentepe",
  "Çamaş",
  "Çatalpınar",
  "Çaybaşı",
  "İkizce",
  "Kabadüz",
  "Kabataş",
  "Altınordu",
  "Ardeşen",
  "Çamlıhemşin",
  "Çayeli",
  "Fındıklı",
  "İkizdere",
  "Kalkandere",
  "Pazar",
  "Rize",
  "Güneysu",
  "Derepazarı",
  "Hemşin",
  "İyidere",
  "Akyazı",
  "Geyve",
  "Hendek",
  "Karasu",
  "Kaynarca",
  "Sapanca",
  "Kocaali",
  "Pamukova",
  "Taraklı",
  "Ferizli",
  "Karapürçek",
  "Söğütlü",
  "Adapazarı",
  "Arifiye",
  "Erenler",
  "Serdivan",
  "Alaçam",
  "Bafra",
  "Çarşamba",
  "Havza",
  "Kavak",
  "Ladik",
  "Terme",
  "Vezirköprü",
  "Asarcık",
  "19.May",
  "Salıpazarı",
  "Tekkeköy",
  "Ayvacık",
  "Yakakent",
  "Atakum",
  "Canik",
  "İlkadım",
  "Baykan",
  "Eruh",
  "Kurtalan",
  "Pervari",
  "Siirt",
  "Şirvan",
  "Tillo",
  "Ayancık",
  "Boyabat",
  "Durağan",
  "Erfelek",
  "Gerze",
  "Sinop",
  "Türkeli",
  "Dikmen",
  "Saraydüzü",
  "Divriği",
  "Gemerek",
  "Gürün",
  "Hafik",
  "İmranlı",
  "Kangal",
  "Koyulhisar",
  "Sivas",
  "Suşehri",
  "Şarkışla",
  "Yıldızeli",
  "Zara",
  "Akıncılar",
  "Altınyayla",
  "Doğanşar",
  "Gölova",
  "Ulaş",
  "Çerkezköy",
  "Çorlu",
  "Hayrabolu",
  "Malkara",
  "Muratlı",
  "Saray",
  "Şarköy",
  "Marmaraereğlisi",
  "Ergene",
  "Kapaklı",
  "Süleymanpaşa",
  "Almus",
  "Artova",
  "Erbaa",
  "Niksar",
  "Reşadiye",
  "Tokat",
  "Turhal",
  "Zile",
  "Pazar",
  "Yeşilyurt",
  "Başçiftlik",
  "Sulusaray",
  "Akçaabat",
  "Araklı",
  "Arsin",
  "Çaykara",
  "Maçka",
  "Of",
  "Sürmene",
  "Tonya",
  "Vakfıkebir",
  "Yomra",
  "Beşikdüzü",
  "Şalpazarı",
  "Çarşıbaşı",
  "Dernekpazarı",
  "Düzköy",
  "Hayrat",
  "Köprübaşı",
  "Ortahisar",
  "Çemişgezek",
  "Hozat",
  "Mazgirt",
  "Nazımiye",
  "Ovacık",
  "Pertek",
  "Pülümür",
  "Tunceli",
  "Akçakale",
  "Birecik",
  "Bozova",
  "Ceylanpınar",
  "Halfeti",
  "Hilvan",
  "Siverek",
  "Suruç",
  "Viranşehir",
  "Harran",
  "Eyyübiye",
  "Haliliye",
  "Karaköprü",
  "Banaz",
  "Eşme",
  "Karahallı",
  "Sivaslı",
  "Ulubey",
  "Uşak",
  "Başkale",
  "Çatak",
  "Erciş",
  "Gevaş",
  "Gürpınar",
  "Muradiye",
  "Özalp",
  "Bahçesaray",
  "Çaldıran",
  "Edremit",
  "Saray",
  "İpekyolu",
  "Tuşba",
  "Akdağmadeni",
  "Boğazlıyan",
  "Çayıralan",
  "Çekerek",
  "Sarıkaya",
  "Sorgun",
  "Şefaatli",
  "Yerköy",
  "Yozgat",
  "Aydıncık",
  "Çandır",
  "Kadışehri",
  "Saraykent",
  "Yenifakılı",
  "Çaycuma",
  "Devrek",
  "Ereğli",
  "Zonguldak",
  "Alaplı",
  "Gökçebey",
  "Kilimli",
  "Kozlu",
  "Aksaray",
  "Ortaköy",
  "Ağaçören",
  "Güzelyurt",
  "Sarıyahşi",
  "Eskil",
  "Gülağaç",
  "Bayburt",
  "Aydıntepe",
  "Demirözü",
  "Ermenek",
  "Karaman",
  "Ayrancı",
  "Kazımkarabekir",
  "Başyayla",
  "Sarıveliler",
  "Delice",
  "Keskin",
  "Kırıkkale",
  "Sulakyurt",
  "Bahşili",
  "Balışeyh",
  "Çelebi",
  "Karakeçili",
  "Yahşihan",
  "Batman",
  "Beşiri",
  "Gercüş",
  "Kozluk",
  "Sason",
  "Hasankeyf",
  "Beytüşşebap",
  "Cizre",
  "İdil",
  "Silopi",
  "Şırnak",
  "Uludere",
  "Güçlükonak",
  "Bartın",
  "Kurucaşile",
  "Ulus",
  "Amasra",
  "Ardahan",
  "Çıldır",
  "Göle",
  "Hanak",
  "Posof",
  "Damal",
  "Aralık",
  "Iğdır",
  "Tuzluca",
  "Karakoyunlu",
  "Yalova",
  "Altınova",
  "Armutlu",
  "Çınarcık",
  "Çiftlikköy",
  "Termal",
  "Eflani",
  "Eskipazar",
  "Karabük",
  "Ovacık",
  "Karabük",
  "Safranbolu",
  "Yenice",
  "Karabük",
  "Kilis",
  "Elbeyli",
  "Musabeyli",
  "Polateli",
  "Bahçe",
  "Kadirli",
  "Osmaniye",
  "Düziçi",
  "Hasanbeyli",
  "Sumbas",
  "Toprakkale",
  "Akçakoca",
  "Düzce",
  "Yığılca",
  "Cumayeri",
  "Gölyaka",
  "Çilimli",
  "Gümüşova",
  "Kaynaşlı",
);

foreach ($iller as $key => $illlerc) {
  $illerx[] = strtolower(turkceToIngilizce($illlerc));

}

foreach ($ilceler as $key => $ilcelerc) {
  $ilcelercc[] = strtolower(turkceToIngilizce($ilcelerc));

}


$negatifAnahtarKelimeler = array();

// Anahtar kelimeleri negatif anahtar kelime listesine ekleyin
foreach ($parcalabir as $anahtarKelimeler) {
    foreach ($anahtarKelimeler as $anahtarKelime) {
        $anahtarKelime = strtolower($anahtarKelime);

        $negatifAnahtarKelimelerx[] = $anahtarKelime;
    }
}
$negatifAnahtarKelimelerxcc = array_merge($negatifAnahtarKelimelerx,$illerx);
$negatifAnahtarKelimeler = array_merge($negatifAnahtarKelimelerx,$ilcelercc);
//print_r($negatifAnahtarKelimeler);
$olmayanlar = array(); // Olmayan terimleri saklamak için boş bir dizi oluşturun
// Aranacak terimleri kontrol edin ve negatif anahtar kelimeleri kaldırın
foreach ($parcala as $aranacakTerimler) {
    foreach ($aranacakTerimler as $aranacakTerim) {
        $aranacakTerim = strtolower($aranacakTerim);

        if (in_array($aranacakTerim, $negatifAnahtarKelimeler)) {

        }else {
          $olmayanlar[] = $aranacakTerim;
        }
    }
}

$olmayanlar = array_unique($olmayanlar);


$olmayanlarlistesi = str_replace($negatifAnahtarKelimeler,"", $olmayanlar);

foreach ($olmayanlarlistesi as $olmayanTerim) {



    $GoogleKeyword = $db->Query('GoogleNegativeWords',['Keywords' => (string)$olmayanTerim], [], 'TEK');


    if ($GoogleKeyword["_id"]=="") {
      $data = array(
        'CompanyCode' => (int)$CompaniesCode,
        'Keywords' => (string)$olmayanTerim,
        'GoogleStatus' => 0,
      );
      $db->Add("GoogleNegativeWords", $data);

    }
}
